# Generated by Django 5.0 on 2023-12-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0003_revokedtoken_alter_customuser_email_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('TUTOR', 'Tutor'), ('STUDENT', 'Student')], default='STUDENT', max_length=50),
        ),
    ]
