# Generated by Django 5.0 on 2023-12-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0004_alter_customuser_password_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('TUTOR', 'Tutor'), ('STUDENT', 'Student')], default='STUDENT', max_length=200),
        ),
    ]
