# Generated by Django 5.0 on 2023-12-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revokedtoken',
            name='token',
            field=models.CharField(max_length=800),
        ),
    ]
