# Generated by Django 5.0 on 2023-12-13 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0006_alter_revokedtoken_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_confirmed',
        ),
    ]
