# Generated by Django 5.0 on 2023-12-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0009_customuser_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_confirmed',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
